#SPRING CONFIGURATION
spring:
  application:
    name: hotel-room-zuul-proxy

server:
  port: 8090

#EUREKA CLIENT CONFIGURATION
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

#ZUUL PROXY CONFIGURATION
zuul:
  routes:
    hotel:
      serviceId: microservices-hotel
      path: /api/hotel/v1/**
    open-room:
      serviceId: microservices-open-room
      path: /api/open-room/v1/**
    hotel-room-composite:
      serviceId: hotel-room-composite
      path: /api/hotel-room/v1/**