#SPRING CONFIG SERVER CONFIGURATION
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/frsknalexis/config-server-hotel-composite-microservices.git
          username: frsknalexis
          password: a06_04_1997a

#EUREKA CLIENT CONFIGURATION
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka